### ISSUE TITLE
Nav server reports "en-us" locale, but currency is GBP when setup

### ISSUE THREAD

**Issue by brooksca** [microsoft/nav-arm-templates#123]
I've run the azuredeploy.json template several times and each time the currency is in GBP with VAT instead of USD and Tax. The region in MySettings is set to United States, but it still appears to be a United Kingdom setup. The extension we're developing will be deployed to US Business Central tenants, so it would be helpful to have a matching development environment. Any help would be appreciated.

**Comment by freddydk** [comment]
How are running the azuredeploy.json template?
What docker image are you specifying?

**Comment by brooksca** [comment]
Hey Freddy,

I'm using the https://aka.ms/getbc link to open the template in Azure. The image that is populated in the template is mcr.microsoft.com/businesscentral/onprem. Below are the parameters I'm using in the template:

Subscription: [My Subscription]
Resource group: [My BCResourceGroup]
Location: (US) East US 2

Vm Name: [Server name]
Timezone Id: Eastern Standard Time
Accept Eula: Yes
Remote Desktop Access: [Client IP]
Operating System: Windows Server 2019 with Containers
Vm Size: Standard_D3_v2
Vm Admin Username: [Username]
BC Admin Username: [Username]
Admin Password: [Password]
BC Docker Image: mcr.microsoft.com/businesscentral/onprem
Assign Premium Plan: No
Create Test Users: No
License File Uri: 
Enable Task Scheduler: Yes
Office365User Name:
Office365Password:
Create Aad Users: No
Bing Maps Key: 
Run Windows Update: No
Contact E Mail For Lets Encrypt: [Email]
Auto Shutdown: Enabled
Auto Shutdown Time: 23:00
Add Traefik: No

**Comment by freddydk** [comment]
The default onprem image is W1, which contains international demo data.
Have you tried to deploy the North American version?
add :NA to the docker image name to get North America.

**Comment by brooksca** [comment]
Added :NA to the end of the image, i.e. 
"BC Docker Image: mcr.microsoft.com/businesscentral/onprem:NA"

VM and auxiliary resources spun up correctly, but on the BC landing page, I'm seeing this:
![image](https://user-images.githubusercontent.com/2266064/63447115-7056d780-c409-11e9-8090-5c9194704d3d.png)

**Comment by freddydk** [comment]
Not sure what the cause of that is - typically the docker name should be lowercase, but I am pretty sure it doesn't matter.
I would delete this and try again.

**Comment by freddydk** [comment]
Actually it does matter - you need to specify :na (lowercase) - sorry.

**Comment by freddydk** [comment]
Did you try with :na - did this fix the issue?

**Comment by freddydk** [comment]
Sounds like you have a Zombie container.
https://freddysblog.com/2019/08/07/zombie-containers-skip-this-build/
One of the comments describes how to get rid of it.

**Comment by brooksca** [comment]
Ended up deleting the Azure resources altogether and re-running the ARM template. The lower-case :na on the end of the container name worked, so you can close this one out. Thanks for all your help.
