### ISSUE TITLE
Git Commands fail for Workshop Machines

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/nav-arm-templates#126]
In script

https://github.com/microsoft/nav-arm-templates/blob/master/additional-install.ps1

the last three lines fail

& git config --global core.safecrlf false
& git config --global user.email "$($vmAdminUsername)@$($hostName)"
& git config --global user.name "$vmAdminUsername"

8:24:26 PM at , C:\demo\setupVm.ps1: line 255
8:24:26 PM at , C:\demo\FinalSetupScript.ps1: line 32
8:24:26 PM The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Perhaps you need the full path to C:\Program Files\Git\bin\git.exe

**Comment by freddydk** [comment]
have included the PR, thanks
