### ISSUE TITLE
Lets Encrypt certificate outdated use of API

### ISSUE THREAD

**Issue by haneiv** [microsoft/nav-arm-templates#133]
Guessing this should be reported to navcontainerhelper, but i post it here.

Running aka.ms/getbc with the template mcr.microsoft.com/businesscentral/onprem:no
with lets encrypt gives this error.

> 12:53:42 PM Restarting computer and start Installation tasks
> 12:53:40 PM Reverting to Self Signed Certificate
> }
> "status": 403
> "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",
> "type": "urn:acme:error:unauthorized",
> + Content: {
> + Code: Forbidden
> +Response from server:
> 12:53:40 PM Unexpected error
> 12:53:20 PM Using Lets Encrypt certificate
> 12:53:20 PM Using Nav Container Helper version 0.6.4.9
> 12:52:56 PM Installing Latest Nav Container Helper from PowerShell Gallery
> 12:52:56 PM Downloading C:\DEMO\Install-VS2017Community.ps1

When trying to download symbols, it gives error regarding the ssl certificate. Since the fallback to self-signed ones instead.

**Comment by freddydk** [comment]
Yep, got this one this morning as well - will fix this today/tomorrow

**Comment by freddydk** [comment]
Updated to ACME v2 now (requires NavContainerHelper 0.6.4.10, which is automatically installed with new instances)
