### ISSUE TITLE
IncludeCSIDE and EnableSymbolLoading should be ignored for v15 containers

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/nav-arm-templates#139]
If you set IncludeCSIDE or EnableSymbolLoading to YES for v15 containers setup will fail.
I think the template should ignore these properties.

**Comment by freddydk** [comment]
If you use http://aka.ms/getbc or http://aka.ms/getbcext - you won't have these properties and the default image is business central latest
If you use http://aka.ms/getnav or http://aka.ms/getnavext - you will have these properties and the default image is nav latest
if you want BC 13 or 14 with CSIDE or symbolloading - you should use getnav.

**Comment by ChrisBlankDe** [comment]
Im using (kind of) http://aka.ms/getnavworkshopvms.
I used PowerShell and had to add IncludeCSIDE and IncludeAL course the latest modification are a breaking change. Thought we can fix this...

```powershell
$TemplateParameterObject = @{
  AcceptEula='Yes' 
  vmName=$RgName
  TimezoneId='W. Europe Standard Time'
  RemoteDesktopAccess='*'
  vmAdminUsername='***'
  navAdminUsername='***'
  adminPassword= '***'
  AssignPremiumPlan= 'Yes'
  CreateTestUsers= 'Yes'
  navDockerImage= 'mcr.microsoft.com/businesscentral/sandbox'
  RunWindowsUpdate='No'
  FinalSetupScriptUrl='https://raw.githubusercontent.com/ChrisBlankDe/nav-arm-extensions/master/AdditionalAppsViaChoco.ps1'
  EnableSymbolLoading = 'No'
  IncludeCSIDE = 'No'
  IncludeAL= 'Yes'
  LicenseFileUri = '***'
  count=78
  offset=10
}
New-AzureRmResourceGroupDeployment -TemplateUri "https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/getnavworkshopvms.json" -ResourceGroupName $RgName  -TemplateParameterObject $TemplateParameterObject -Name "$($RgName)Deploy" -Mode Incremental
```

**Comment by freddydk** [comment]
got you - yes, for that one you probably need:

    $Parameters.Add("RunWindowsUpdate", "Yes")
    $Parameters.Add("IncludeAL", "No")
    $Parameters.Add("IncludeCSIDE", "Yes")
    $Parameters.Add("ClickOnce", "Yes")
    $Parameters.Add("AssignPremiumPlan", "No")
    $Parameters.Add("CreateTestUsers", "No")
    $Parameters.Add("EnableSymbolLoading", "No")

I might create a BC version of that as well.

BTW - this morning I checked in a change, which allows you to transfer a series of passwords seperated by comma to the adminpassword field.
Passwords will be assigned to the VMs from this list using $passwords[$no -mod $count] - meaning if you have just one password, nothing changes - but you can supply unique passwords for all VMs
Only thing that doesn't work is that you cannot have a comma in a password.

**Comment by ChrisBlankDe** [comment]
Just an Idea: Maybe we should change this in navcontainerhelper or docker image.
Just throwing a warning when a user is using an parameter which makes no sense and ignore it.
This would make standardization much easier. Currently i have three different property sets (hybrid/FullApp/IsvEmbed) for container creation.


> Only thing that doesn't work is that you cannot have a comma in a password.

Saw it. Hope this wont be the source of to many error. Maybe we should pair this with an yes/no property?!

**Comment by freddydk** [comment]
It is only for the navworkshops template - it doesn't affect the other ones (which are the ones being used mostly).
IMO the properties are not due to container version - it is whether or not you use that in a project.
If your project is hybrid you need some settings - and cannot live without them. This is really the reason for the error - if you ask for symbolloading, then containerhelper should fail. Else you will discover something not working much much later.
