### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/nav-arm-templates#163]
Not sure what I am doing wrong. Tried http://aka.ms/getbc three times and got this error message. I've created hundreds of these VMs over the years so I think I know what I'm doing but I can't get it to work.
![image](https://user-images.githubusercontent.com/23434319/112090457-d27d3e80-8b50-11eb-83c9-6704a475799a.png)
![image](https://user-images.githubusercontent.com/23434319/112090540-fb9dcf00-8b50-11eb-89cf-af25583550e8.png)

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'vmextension1'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'PackageManagement\\Install-Package : No match was found for the specified search criteria and module name \r\n'powershellget'. Try Get-PSRepository to see all available registered module repositories.\r\nAt C:\\Program Files\\WindowsPowerShell\\Modules\\PowerShellG...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}

**Comment by freddydk** [comment]
Could be that something has changed.
Will try to create one myself.

**Comment by TheDenSter** [comment]
Did you get a chance to look at that? I am taking Waldo's DevOps class this week and it would be nice to be able to do the exercises and follow along with his demos

**Comment by freddydk** [comment]
Should be fixed now- just checked in 2 minutes ago and will try myself

**Comment by TheDenSter** [comment]
Thanks Freddy, I appreciate you looking at that right away. It deployed as expected this morning and everything works.
