### ISSUE TITLE
Nice 2 Have - Add 7zip to additional-installforbuildagent.ps1

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/nav-arm-templates#166]
Hi Freddy,

this is a small wish: Do you mind adding 7zip to additional-installforbuildagent.ps1 ? Since you install choco anyway that should be a small thing to do, or?
I recall reading that 7zip makes a couple of things faster compared to the normal zip.

It is just an idea :)

**Comment by freddydk** [comment]
Good idea
