### ISSUE TITLE
getBcExt and getBc template with office 356 integration Error

### ISSUE THREAD

**Issue by DOM-Log** [microsoft/nav-arm-templates#169]
Hello
I encountered a Error while creating a environment with the getBcExt and getBc Template when I create it with "Office365User Name" and "Office365Password".

If you need any more details, please reach out to me.

![MicrosoftTeams-image (1)_LI](https://user-images.githubusercontent.com/92917994/138249501-a83a12a5-6afc-4b2c-8d5d-675c02b847e1.jpg)

**Comment by bydynamics** [comment]
Hi folks. Any updates on this matter?

**Comment by marknitek** [comment]
@freddydk when will this issue be resolved or is there a workaround? Its bad that we are not able to create o365 integrated demo environments.
