### ISSUE TITLE
Container memory limit configuration in ARM template

### ISSUE THREAD

**Issue by florinangelescu** [microsoft/nav-arm-templates#185]
When not using a parameter for the container maximum memory and using Isolation option, the container gets a default of 8 GB maximum memory allocated.

We found in script SetupNavContainer.ps1 that we could add a -memoryLimit parameter to New-NavContainer cmdlet on line 340.
However, there is no parameter to configure this value in the ARM template (getbcext.json), so the -memoryLimit addition would be a hardcoded workaround (which we would like to avoid).

How can we configure the value of the container memory limit using a parameterized and flexible approach?

**Comment by freddydk** [comment]
If you use https://aka.ms/getbcext (extended version) it has a parameter called **BeforeSetupContainerSetupScriptUrl**
You can set that to the URL of a script in which you create a setup file **c:\programdata\bccontainerhelper\bccontainerhelper.config.json**, which contains setup for **DefaultNewContainerParameters** and setup memoryLimit to what you need.
A bit cumbersome, but using this mechanism you can basically change everything yourself.

**Comment by bogdanurse** [comment]
@freddydk Did you changed something into the module regarding the container memory? After this post all our containers are being created with the size of the VM itself. For example if VM=32GB -> docker memory = 32 gb. If VM=16GB -> docker memory =16GB

**Comment by freddydk** [comment]
@bogdanurse - didn't see this.
I don't think I changed anything - it sounds like your containers are created using process isolation (which will, unless specifically specified otherwise) will allow containers to use all memory from the host (like any other process)
