### ISSUE TITLE
Error during deploy of  BC Standard from ARM template 

### ISSUE THREAD

**Issue by ManuelvdM** [microsoft/nav-arm-templates#195]
When using aka.ms/getbc we get an error at the end of the deployment.
We tested this with a couple of different scenario's. 
1. Standard with aka.ms/getbc
2. From a release pipeline using the ARM templates
3. And creating a new container on a new environment with SetupNAVContainer.ps1

All result in the same error.

3:08:03 PM at , C:\demo\setupVm.ps1: line 384
3:08:03 PM at , C:\demo\SetupNavContainer.ps1: line 422
3:08:03 PM at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\4.0.6\AppHandling\Publish-NavContainerApp.ps1: line 144
3:08:03 PM at , C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\4.0.6\AppHandling\Publish-NavContainerApp.ps1: line 293
3:08:03 PM at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\4.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 112
3:08:03 PM The tenant 'default' is not accessible, because it is in state Mounting.
2:49:38 PM Running container (this might take some time)
2:49:38 PM Locale nl-NL
2:49:38 PM Version 21.1.48363.49129
2:49:38 PM Country nl

When investigating this issue, we found out the the problem is in the SetupNAVContainer.ps1. 
On the Publish-NavContainerApp. If we addd a start-sleep before the publish-navcontainerapp it will continue without an error.

![image](https://user-images.githubusercontent.com/55435758/201318466-54479e22-f5b5-4948-bc74-5e3dac4bbebe.png)

**Comment by ManuelvdM** [comment]
[settings.txt](https://github.com/microsoft/nav-arm-templates/files/9989623/settings.txt)

**Comment by freddydk** [comment]
This was fixed shortly after
