### ISSUE TITLE
aka.ms/getbcext internal server error

### ISSUE THREAD

**Issue by Mkublbock** [microsoft/nav-arm-templates#220]
When navigating to [aka.ms/getbcext](url) it shows an internal error: 

> There was an error downloading the template from URI 'https://freddyk.azurewebsites.net/api/MergeArmTemplate'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

When trying to copy the entire script and using custom deployment there is an error creating the deployment because TemplateLink cannot be used localy

**Comment by freddydk** [comment]
Assuming that this was a temporary problem.
