### ISSUE TITLE
Azure VM with Azure SQL deployment fails

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-arm-templates#39]
Location: West Europe
Size: Standard_D2_v3
Admin Pass: Complex password chosen...
Image: microsoft/bcsandbox:gb
SQL: AzureSQL
Win Upate: No
Lets Encrypt: Yes

The deployment fails with the following message -

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Unable to process template language expressions for resource '/subscriptions/**MASKED**/resourceGroups/TSGTESTD365BC/providers/Microsoft.Sql/servers/sqltsgtestd365bc/databases/App/extensions/Import' at line '1' and column '7615'. 'The language expression property array index '1' is out of bounds.'\"\r\n }\r\n}"},{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Unable to process template language expressions for resource '/subscriptions/**MASKED**/resourceGroups/TSGTESTD365BC/providers/Microsoft.Sql/servers/sqltsgtestd365bc/databases/Tenant/extensions/Import' at line '1' and column '8657'. 'The language expression property array index '1' is out of bounds.'\"\r\n }\r\n}"}]}

**Comment by AlphaGeeKUK** [comment]
The VM has spun up ok but the installation of the D365 BC element is failing - from View Installation Status

12:12:13 PM Login failed for user 'sqladmin'.

**Comment by freddydk** [comment]
Did you specify an app bacpac uri and a tenant bacpac uri?

**Comment by AlphaGeeKUK** [comment]
No.

**Comment by AlphaGeeKUK** [comment]
Thanks. I missed that. I'll close this issue and build a new instance.
