### ISSUE TITLE
Integrate auto-shutdown configuration in ARM template deployments for Azure VMs

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-arm-templates#41]
Is it possible to enable the VM Auto Shutdown configuration from Template Switch?

Here is a like with some ARM snippets to do this:
https://www.danielstechblog.info/integrate-auto-shutdown-configuration-arm-template-deployments-azure-vms/

**Comment by freddydk** [comment]
Good idea - will implement this

**Comment by freddydk** [comment]
Implemented
