### ISSUE TITLE
Docker Problems with Windows Server 2019

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-arm-templates#72]
**Build Agent Template**

The Problems during container creation:
![image](https://user-images.githubusercontent.com/15800069/49294999-e058b280-f4b4-11e8-9867-114a4ca8b47d.png)
Used OS:
![image](https://user-images.githubusercontent.com/15800069/49295054-0b430680-f4b5-11e8-9b4a-443b96e98d41.png)

**Comment by freddydk** [comment]
Has this been resolved?

**Comment by megel** [comment]
I assume, it depends on the `useBestContainerOS` Parameter. Since I have changed this to `$false` it works.

```PowerShell
# the relevant Parameters:
$additionalParameters += @("--volume ""${workspaceFolder}:${workspaceFolder}""", "--env httpSite=N", "--env WebClient=N")
$myscripts = @(@{'MainLoop.ps1' = 'while ($true) { start-sleep -seconds 10 }'})
$shortcuts = "None"
$useBestContainerOS = $true   # set during some other stuff

New-NavContainer @parameters `
                        -containerName $containerName `
                        -imageName "$($imageversion.containerImage)" `
                        -auth NAVUserPassword `
                        -Credential $credential `
                        -alwaysPull:$imageversion.alwaysPull `
                        -updateHosts `
                        -includeCSide `
                        -doNotExportObjectsToText `
                        -enableSymbolLoading `
                        -useBestContainerOS:$useBestContainerOS `
                        -shortcuts $shortcuts `
                        -licenseFile "$licenseFile" `
                        -additionalParameters $additionalParameters `
                        -myScripts $myscripts
```

**Comment by freddydk** [comment]
and you have navcontainerhelper 0.4.2.2?

**Comment by megel** [comment]
ContainerHelpers should be the highest … `Install-NavContainerHelper` is running first.

But I'll check again - the new Server2019 is currently in creation :) … take some minutes

**Comment by megel** [comment]
Oh, Server 2019 fails on before New-Container:
![image](https://user-images.githubusercontent.com/15800069/49405616-3480c280-f753-11e8-8ee5-509512740092.png)
Strange - the second run of the build Pipeline runs - don't know what happened?

No - it runs into the same error:
![image](https://user-images.githubusercontent.com/15800069/49405911-4747c700-f754-11e8-939a-1fbb66fa3681.png)

and I have used: **microsoft/bcsandbox:de**

**Comment by freddydk** [comment]
I will try to set this up myself today.

**Comment by freddydk** [comment]
This specific error seems to be because docker isn't running on the agent - I had the same.
Connected to the agent with rdp - started the docker service (I might just include a start-service docker in one of the scripts).
after that - success (very first run takes 25:42)
![image](https://user-images.githubusercontent.com/10775043/49421953-3a49c880-f792-11e8-9dd5-890b5c3b4af9.png)
second run - way faster (image already downloaded and vsts task already installed)
![image](https://user-images.githubusercontent.com/10775043/49422261-7f222f00-f793-11e8-9356-b0763973fba2.png)

**Comment by freddydk** [comment]
I am adding a new option (to use Windows Server 2019 with Containers) - this cuts the initial build down with 7-8 minutes to 18 minutes. The following builds are similar in perf.
![image](https://user-images.githubusercontent.com/10775043/49424248-52254a80-f79a-11e8-96b3-e93eecc5b8c4.png)

**Comment by freddydk** [comment]
Unfortunately, the hosted Windows Container Azure DevOps pool is still on 1803 - meaning that creation of build container will pull 2016 and spin up a 1803 container with the 2016 dvd image extract:
```
[section]******************************************************************************
[section]Starting: Create Build Container
[section]******************************************************************************
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.140.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
Generating script.
Formatted command: . 'D:\_work\1\s\scripts\Create-Container.ps1' -version "current" -credential ([PSCredential]::new("***", (ConvertTo-SecureString -String "***" -AsPlainText -Force))) -licenseFile "***"
[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\_work\_temp\362e401d-d7c6-47e0-8a80-30bac61ca619.ps1'"
Create helloworld-bld from microsoft/bcsandbox:us
Host is Windows 10 10.0.17134.0 - 1803
Pulling image microsoft/bcsandbox:us-ltsc2016
us-ltsc2016: Pulling from microsoft/bcsandbox
3889bb8d808b: Pulling fs layer
900b07d43172: Pulling fs layer
d5f1862af3b5: Pulling fs layer
cce31346ada7: Pulling fs layer
```
Which isn't very fast...

**Comment by freddydk** [comment]
The machine might have restarted and thereby started docker.

**Comment by megel** [comment]
Windows 2019 with Containers … Fresh Setup with FinalSetupScript ... OK
![image](https://user-images.githubusercontent.com/15800069/49440272-7e08f600-f7c3-11e8-8bc5-200ab6db05eb.png)

**Comment by megel** [comment]
It seems the issue has disappeared.

**Comment by freddydk** [comment]
thanks
