### ISSUE TITLE
Docker LSTC2019 problem

### ISSUE THREAD

**Issue by epernst** [Microsoft/nav-arm-templates#74]
When trying to create the latest sandbox using docker on a WS2019.

I'm getting this error:

_Host is Windows Server 10.0.17763.0 - ltsc2019
Pulling image mcr.microsoft.com/businesscentral/sandbox:latest
latest: Pulling from businesscentral/sandbox
Using image mcr.microsoft.com/businesscentral/sandbox:latest
Removing C:\ProgramData\NavContainerHelper\Extensions\BC-Sandbox
Creating Nav container BC-Sandbox
Using license file C:\ProgramData\bcEnvironmentHelper\BC2018FALLdk.flf
NAV Version: 13.1.25940.26323-W1
Generic Tag: 0.0.8.0
Container OS Version: 10.0.14393.2608 (ltsc2016)
Host OS Version: 10.0.17763.0 (ltsc2019)
A better Container OS exists for your host (ltsc2019)
generic-ltsc2019: Pulling from microsoft/dynamics-nav
Creating container BC-Sandbox from image microsoft/dynamics-nav:generic-ltsc2019
84cd1e54676fd2440ff39057a7b0b5d2ec964a5ec473ed6d739b6a934940d6e5
Waiting for container BC-Sandbox to be ready
Installing Business Central
Downloading Url Rewrite
Installing Url Rewrite
Downloading OpenXML
Installing OpenXML
Downloading DotNetCore
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files_
Copying PowerShell Scripts
Cannot find path 'C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration\' because it does not exist.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 69
at <ScriptBlock>, C:\Run\start.ps1: line 108
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central

I checked the NAVAdministration folder in the container, and it's empty.

**Comment by freddydk** [comment]
what ARM template did you use? (http://aka.ms/???)
What Docker image did you specify?
If you could send me an email with the landing page of the VM and maybe the credentials - then I can see if this is a special case I didn't take into account.

Thanks

**Comment by epernst** [comment]
Error has resolved it selves. When I ran it again, then it was (by it selves) using mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019, which did not fail. So must have been a glitch!
