### ISSUE TITLE
Codeunit 50000 stays in database

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [Microsoft/nav-arm-templates#75]
Hello,
after the automatic configuration of the BC Container there codeunit 50000 stays in database.

If you want to publish an App which is including codeunit 50000 you'll receive an error, "An application object of type 'Codeunit' with ID '50000' is already declared"

The NAVContainerHelper does not support deleting objects.

Best regards

**Comment by megel** [comment]
Patrick, remember there are hidden objects in (I guess) demo / example extensions between ID 50000..5000x

**Comment by freddydk** [comment]
If you have checked the Create Test Users flag in the ARM template, then that will indeed import a fob file with object 50000 and use that.
