### ISSUE TITLE
BingMaps not working in getbc

### ISSUE THREAD

**Issue by ichladil** [Microsoft/nav-arm-templates#81]
When creating an environment via http://aka.ms/getbc and using BingMapsKey, the docker startup fails with error message:

> Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'directionswe.blob.core.windows.net'"

This seems to happen in  NavContainerSetup.ps1 due to the invalid link in http://aka.ms/bingmaps.app

**Comment by freddydk** [comment]
Seems like my cleanup was too effective, will make this work again within the next days

**Comment by freddydk** [comment]
Should work again now
