### ISSUE TITLE
Exception calling "DownloadFile" with "2" argument(s) during setupVM

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-arm-templates#82]
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."

Used Template:
`https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/getbcext.json`

* Windows Server 2019 with Containers
* mcr.microsoft.com/businesscentral/onprem:de

Error:
![image](https://user-images.githubusercontent.com/15800069/52800212-94f97d80-307b-11e9-8cdd-ff7f13121056.png)

**Comment by freddydk** [comment]
Looks like the license file Uri is wrong.
Line 552 here: https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-NavContainer.ps1

**Comment by megel** [comment]
Arg! Dman - my fault the file wasn't there :)
