### ISSUE TITLE
The template deployment 'Microsoft.Template' is not valid according to the validation procedure

### ISSUE THREAD

**Issue by MikkelLevin** [Microsoft/nav-arm-templates#83]
Currently we get the following error creating new vm's using aka.ms/getnav with image='microsoft/bcsandbox:dk'

'Error submitting the deployment request.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '8621c3ef-5b6f-4741-919c-6de6d4ff79c7'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.'

**Comment by freddydk** [comment]
This is not a general problem. It looks like you have entered something which is invalid.
If this still fails, you would need to give me all the information you have entered in all fields.

**Comment by MikkelLevin** [comment]
Thanks for helping. Plese find the info we have entered in the template. Thanks.
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "value": "MdcBcDev0000006"
    },
    "TimezoneId": {
      "value": "W. Europe Standard Time"
    },
    "AcceptEula": {
      "value": "Yes"
    },
    "RemoteDesktopAccess": {
      "value": "87.54.57.201"
    },
    "OperatingSystem": {
      "value": "Windows Server 2019 with Containers"
    },
    "vmSize": {
      "value": "Standard_D4_v3"
    },
    "vmAdminUsername": {
      "value": "vmadmin"
    },
    "navAdminUsername": {
      "value": "admin"
    },
    "adminPassword": {
      "value": "*** Hidden ***"
    },
    "navDockerImage": {
      "value": "microsoft/bcsandbox:dk"
    },
    "LicenseFileUri": {
      "value": "*** Hidden ***"
    },
    "ClickOnce": {
      "value": "No"
    },
    "EnableTaskScheduler": {
      "value": "Yes"
    },
    "Office365UserName": {
      "value": "*** Hidden ***"
    },
    "Office365Password": {
      "value": "*** Hidden ***"
    },
    "CreateAadUsers": {
      "value": "Yes"
    },
    "BingMapsKey": {
      "value": ""
    },
    "RunWindowsUpdate": {
      "value": "No"
    },
    "ContactEMailForLetsEncrypt": {
      "value": "*** Hidden ***"
    },
    "AutoShutdown": {
      "value": "Enabled"
    },
    "AutoShutdownTime": {
      "value": "23:59"
    }
  }
}

**Comment by freddydk** [comment]
Tried the same - works fine
Must be an error in some of your hidden fields.
If you could try to only fill out the mandatory fields in the template - and then figure out what actually causes the issue?
Maybe also try sith a shorter VM name.

**Comment by MikkelLevin** [comment]
Solved.
Think it was a core quota problem. Selecting another vmsize solved the problem.
Thanks.
