### ISSUE TITLE
Install VSIX (AL) fails during SetupVM

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-arm-templates#85]
Got this error re-running of `SetupVM.ps1` on a VM … and used the template `GetBCExt.json`

```PowerShell
[H]0;C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [?25h [H]0;Administrator: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe  [H
Code.cmd : (node:608) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
At C:\demo\SetupDesktop.ps1:59 char:9
+         & $codeCmd @('--install-extension', $VsixFileName) | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ((node:608) [DEP...ethods instead.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

It seams to me, that VSCode may had an update?

VSIX is there: 
```PowerShell
PS C:\DEMO> Get-Item $vsixFileName
    Directory: C:\ProgramData\navcontainerhelper\Extensions\navserver
Mode                LastWriteTime         Length Name                                                                                                                                                               ----                -------------         ------ ----
-a----        1/17/2019   1:52 PM       46487932 al-2.1.79379.vsix     
```

![image](https://user-images.githubusercontent.com/15800069/53594210-aa51ca00-3b9a-11e9-9e25-e1efd6265d2f.png)

**Comment by megel** [comment]
@freddydk, however, install AL vsix throw an error: 
![image](https://user-images.githubusercontent.com/15800069/53595205-ee45ce80-3b9c-11e9-81d4-7e4cefb398e9.png)
but it`s still installed.

With VSCode - everything works well:
![image](https://user-images.githubusercontent.com/15800069/53594839-08cb7800-3b9c-11e9-97e4-6e71c3556681.png)
![image](https://user-images.githubusercontent.com/15800069/53594823-00733d00-3b9c-11e9-9d67-ff2413c075be.png)

Maybe this is an solution:
![image](https://user-images.githubusercontent.com/15800069/53595072-973ff980-3b9c-11e9-86db-6ea60ad3a36a.png)

**Comment by freddydk** [comment]
I have added the try catch to avoid the warning,
