### ISSUE TITLE
Support for Azure DevTest Lab

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-arm-templates#99]
I would like to add the arm templates to azure Dev/Test Lab to have a better control over thins like start/stop and to have all these vms in one place (we use dev/test to organize all other vms in azure that fall in that category). 

Unfortunatly the structure of this repo does not allow this right now. 
According to the docs: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/lab-services/devtest-lab-create-environment-from-arm.md the template files must be seperated in folders and must be named `azuredeploy.json` like in the default repo https://github.com/Azure/azure-devtestlab/tree/master/Environments

@freddydk  are you willing to support this scenario?

**Comment by freddydk** [comment]
I will have a look at that and get back

**Comment by freddydk** [comment]
I played around with this today and have created one template, which works.
If you setup a private repo for templates like this:
![image](https://user-images.githubusercontent.com/10775043/62006382-4aa71d00-b140-11e9-9c50-fea972bdb3b4.png)
Then you should be able to deploy.
You can also create your own github repo and grab the files from the Environments/getbc folder, and change parameters, default them etc. and then spin up your machines with that.

**Comment by marknitek** [comment]
Perfect thanks a lot i will give it a try!

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/62007556-2f8fd980-b14f-11e9-8ee0-76d68767633a.png)
